### ISSUE TITLE
Checkpoint Error.

### ISSUE THREAD

**Issue by WGC575** [usc-softarch/arcade_core#101]
After processing 1300 issues, it broke down due to not recognizing "INCIDENT" issue type:
![image](https://user-images.githubusercontent.com/8021429/229207120-a961f140-13e2-419e-afdd-2ea13ae80a6f.png)

When building the project again with or without code changes, and run it again with the same script, it will throw a NoClassDefFoundError exception:
![image](https://user-images.githubusercontent.com/8021429/229207411-66676530-0f5c-410b-82bc-b2a0e81db5b9.png)

I feel this is not I need to worry at current point, since I can run it from the beginning, but I think it's something that we need to check later.

**Comment by MarceloLaser** [comment]
The first image cuts off the most important part of the exception message, but I take it you've already identified and fixed the missing tag? Also, just to double-check, are you sure you're running the jar with dependencies when you get the second issue? That exception indicates that one of the classes used for parsing in the issuesCheckpoint.json file was missing, and that is a method I use regularly in my own executions so it _should_ be working fine. If you _are_ using the jar with dependencies when getting that issue, then I will need to verify it.

**Comment by WGC575** [comment]
> The first image cuts off the most important part of the exception message, but I take it you've already identified and fixed the missing tag? Also, just to double-check, are you sure you're running the jar with dependencies when you get the second issue? That exception indicates that one of the classes used for parsing in the issuesCheckpoint.json file was missing, and that is a method I use regularly in my own executions so it _should_ be working fine. If you _are_ using the jar with dependencies when getting that issue, then I will need to verify it.

Thanks for the reply, I will double check to make sure. I'm running the script again with some code modifications. I will let you know if I can't fix it myself.

**Comment by WGC575** [comment]
By the way, the screenshot is fully captured, but the log itself is cut off by VSCode. I need to reproduce the problem and try to get the full error info.

**Comment by WGC575** [comment]
@MarceloLaser Hi Marcelo! After I modified the code, it's now giving an NullPointerException for file reader. In addition, when I tried to run the script again, it would give the same error. I'm trying to figure out the root cause for this. I wonder do you have any idea about the potential cause?

The cmd log:

```bash
PS D:\Workspace\arc-sum\arcade> java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.RecovArEngine "gitlab_subjects/clusters/inkscape/acdc" "gitlab_subjects/clusters/inkscape/versionTree.rsf" 3472737 "gitlab_subjects/clusters/inkscape/issuesCheckpoint.json" "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" "gitlab_subjects/clusters/inkscape/recovArOutput.json"
2023/03/31 13:08:15: Started processing issues for project ID 3472737
No record located, running full scan.
2023/03/31 13:10:13: Finished processing 100 issues.
2023/03/31 13:11:30: Finished processing 200 issues.
2023/03/31 13:13:03: Finished processing 300 issues.
2023/03/31 13:14:18: Finished processing 400 issues.
2023/03/31 13:15:31: Finished processing 500 issues.
2023/03/31 13:16:50: Finished processing 600 issues.
2023/03/31 13:18:23: Finished processing 700 issues.
2023/03/31 13:20:11: Finished processing 800 issues.
2023/03/31 13:21:41: Finished processing 900 issues.
2023/03/31 13:23:16: Finished processing 1000 issues.
2023/03/31 13:24:45: Finished processing 1100 issues.
2023/03/31 13:26:17: Finished processing 1200 issues.
2023/03/31 13:27:48: Finished processing 1300 issues.
2023/03/31 13:29:23: Finished processing 1400 issues.
2023/03/31 13:30:41: Finished processing 1500 issues.
2023/03/31 13:32:19: Finished processing 1600 issues.
2023/03/31 13:33:55: Finished processing 1700 issues.
2023/03/31 13:35:57: Finished processing 1800 issues.
2023/03/31 13:37:33: Finished processing 1900 issues.
2023/03/31 13:38:50: Finished processing 2000 issues.
2023/03/31 13:40:56: Finished processing 2100 issues.
2023/03/31 13:42:30: Finished processing 2200 issues.
2023/03/31 13:43:52: Finished processing 2300 issues.
2023/03/31 13:45:10: Finished processing 2400 issues.
2023/03/31 13:46:27: Finished processing 2500 issues.
2023/03/31 13:49:01: Finished processing 2700 issues.
2023/03/31 13:50:26: Finished processing 2800 issues.
2023/03/31 13:51:25: Finished processing 2900 issues.
2023/03/31 13:52:54: Finished processing 3000 issues.
2023/03/31 13:54:15: Finished processing 3100 issues.
2023/03/31 13:55:31: Finished processing 3200 issues.
2023/03/31 13:57:00: Finished processing 3300 issues.
2023/03/31 13:58:45: Finished processing 3400 issues.
2023/03/31 14:00:17: Finished processing 3500 issues.
2023/03/31 14:01:43: Finished processing 3600 issues.
2023/03/31 14:02:59: Finished processing 3700 issues.
2023/03/31 14:04:22: Finished processing 3800 issues.
2023/03/31 14:05:44: Finished processing 3900 issues.
2023/03/31 14:07:20: Finished processing 4000 issues.
2023/03/31 14:08:57: Finished processing 4100 issues.
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at edu.usc.softarch.arcade.clustering.data.ReadOnlyArchitecture.readFromRsf(ReadOnlyArchitecture.java:405)
        at edu.usc.softarch.arcade.facts.ChangeAnalyzer.<init>(ChangeAnalyzer.java:26)
        at edu.usc.softarch.arcade.facts.design.ElementChangeAnalyzer.<init>(ElementChangeAnalyzer.java:17)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:91)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.getDecisions(RecovArEngine.java:77)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.runWithGitLab(RecovArEngine.java:48)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.main(RecovArEngine.java:21)
PS D:\Workspace\arc-sum\arcade> java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.RecovArEngine "gitlab_subjects/clusters/inkscape/acdc" "gitlab_subjects/clusters/inkscape/versionTree.rsf" 3472737 "gitlab_subjects/clusters/inkscape/issuesCheckpoint.json" "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" "gitlab_subjects/clusters/inkscape/recovArOutput.json"
2023/03/31 14:11:58: Started processing issues for project ID 3472737
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at edu.usc.softarch.arcade.clustering.data.ReadOnlyArchitecture.readFromRsf(ReadOnlyArchitecture.java:405)
        at edu.usc.softarch.arcade.facts.ChangeAnalyzer.<init>(ChangeAnalyzer.java:26)
        at edu.usc.softarch.arcade.facts.design.ElementChangeAnalyzer.<init>(ElementChangeAnalyzer.java:17)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:91)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.getDecisions(RecovArEngine.java:77)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.runWithGitLab(RecovArEngine.java:48)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.main(RecovArEngine.java:21)
PS D:\Workspace\arc-sum\arcade>
```

**Comment by MarceloLaser** [comment]
The root cause is Lines 88-89 of `RecovArEngine`. The `versionMap` doesn't contain entries for the some or all keys provided in the `versionTree.rsf` file. This means that either the `versionTree.rsf` is incorrect, or the `versionMap` is being loaded incorrectly. Given that I recently made a change to how `versionMap` is loaded, I am guessing that will be the cause of the issue.

Please attach a zip with the directory containing:
- the `_clusters.rsf` files you are using as input;
- your `issuesCheckpoint.json` and `versionTree.rsf`;
- the `ARCADE_Core.jar` you're using, and;
- the CMD command you are using to execute RecovAr.

It is likely very easy to fix (probably an incorrect regex somewhere, most ARCADE issues stem from String comparisons...), but identifying exactly what the faulty code is will be much quicker with an input I can run through it. Also having your `ARCADE_Core.jar` will allow me to inspect whether or not it packaged correctly, i.e. whether or not I messed something up in Maven's pom.

Between later today and tomorrow I should have time to debug this and verify both this issue and the issue you were having with SoftArch's JSON package.

**Comment by WGC575** [comment]
@MarceloLaser Here is the [zip file](https://drive.google.com/file/d/1Dy15hAKE9qq879K9gvrNK9xTaE7KrMEr/view?usp=sharing)
The issuesCheckpoint.json and the versionTree.rsf is in /gitlab_subjects/clusters/inkscape/, the ARCADE_Core.jar and the command is in the root directory of the zip file.

Thanks,
Jin

**Comment by WGC575** [comment]
One more comment: There were only 4199 issues when I run the script. So, the script would never have got to the 4200 checkpoint anyway.

**Comment by MarceloLaser** [comment]
The issue the `versionTree.rsf`. The versions listed there are not versions that exist in Inkscape: see image below.

<img width="287" alt="Capture" src="https://user-images.githubusercontent.com/7095289/229374233-ca0eb722-0cdb-441b-b29b-2903232dc79d.PNG">

The latest version available is version 1.2.2. The `versionTree.rsf` versions must correspond to the versions used in the recovery step. The ideal solution here would be to give the user an option to use ARCADE's own version ordering and assume linear progression rather than an actual version tree with multiple branching paths. Unfortunately I don't have the time to implement and test this right now, so for now I've created a generator to make a `versionTree.rsf` file to be used as input. The usage is:

```
java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.VersionTreeGenerator <PATH_TO_CLUSTERS_INPUT> <PATH_TO_VERSIONTREE_OUTPUT>
```

So for example:

```
java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.VersionTreeGenerator arcade_issue_101\gitlab_subjects\clusters\inkscape\acdc arcade_issue_101\gitlab_subjects\clusters\inkscape\versionTree.rsf
```

This will overwrite the existing `versionTree.rsf` with a valid, linear one. That way you don't have to manually write one.

I'm leaving this issue open as a reminder to replace this with a proper optional `versionTree.rsf` argument solution.

**Comment by MarceloLaser** [comment]
I realize another issue comes up with Inkscape: the tags used for versioning are... unorthodox. See link below for example:

https://gitlab.com/api/v4/projects/3472737/repository/commits/7d1146667a10d4f8beb663350f5810a0f9c3e8cd/refs?type=tag&per_page=100

RecovAr expects those tags to look the same as the version strings, that is, to follow the same regular expression. For example, see this commit's tags from Graphviz:

https://gitlab.com/api/v4/projects/4207231/repository/commits/c2375cf30f97ed63885092d4d2ce9c127bd45e9c/refs?type=tag&per_page=100

Therefore, some clean-up of the tags will be required for RecovAr to recognize them. I haven't the time to do this unfortunately, as it is non-trivial to make a sufficiently encompassing solution to this problem. @WGC575 I propose three options here, in increasing order of difficulty:

- You can shift over to using Graphviz as your pilot test subject, since that one is sure to work.
- If you are able to write a method that sanitizes Inkscape's version strings, I can create a reflexive hook into RecovAr for you to load that method in for your analysis. This would effectively be a plugin for RecovAr.
- Alternatively, if you can create a better solution than the current one (using the GitLab REST API endpoint shown above) to identify the versions involved in fixing an issue, we can discuss how to implement that instead.

**Comment by WGC575** [comment]
@MarceloLaser Thank you very much!

**Comment by WGC575** [comment]
@MarceloLaser Hi Marcelo, with the information in the earlier message, I have got the full issue information from Inkscape, but as you have mentioned, recovAr won't give correct results. I'm using the previous recovAr output file you shared with me right now.

I wonder if you have the project data for Graphviz. The data file you shared with me (gitlab_subjects.7z) only contains data for Inkscape. Or, is there a way for me to get the data on my machine?

**Comment by MarceloLaser** [comment]
This was resolved offline, discussion not relevant.
