### ISSUE TITLE
Manual and Documentation

### ISSUE THREAD

**Issue by WGC575** [usc-softarch/arcade_core#106]
I will add documentations as I learn and understand each component of ARCADE.

**Comment by MarceloLaser** [comment]
I updated the documentation and added a "tentative" generic renamer.py, since the original renamer.py was pretty hard-coded. I did _not_ test renamer.py, so I recommend doing that before merging this branch.

Also, the docs make reference to a major difference in run_clustering.py. Could I have access to the new version of it? It may be better to, instead of merging those functions into run_clustering.py, create another script that encapsulates all of those functions. The reason for keeping these scripts separate is to minimize re-runs when something crashes, so combining all those phases into a single script may be counter-productive for some problematic subject systems.

**Comment by WGC575** [comment]
> I updated the documentation and added a "tentative" generic renamer.py, since the original renamer.py was pretty hard-coded. I did _not_ test renamer.py, so I recommend doing that before merging this branch.
> 
> Also, the docs make reference to a major difference in run_clustering.py. Could I have access to the new version of it? It may be better to, instead of merging those functions into run_clustering.py, create another script that encapsulates all of those functions. The reason for keeping these scripts separate is to minimize re-runs when something crashes, so combining all those phases into a single script may be counter-productive for some problematic subject systems.

@MarceloLaser Hi Marcelo, could you give more information about the "major difference" you mentioned? Since I didn't update run_clustering.py, there might be some misunderstanding of the code from my side.

**Comment by MarceloLaser** [comment]
My mistake, I misunderstood the documentation. Going back to it, your description is correct, just missing some context. I've pushed another commit to add that context. It is still missing instructions on some of the scripts, but I assume those will come later. It could also use a script for RecovAr, I'll see if I get the time to make one. Thanks for putting this together!
